@ECHO OFF

ECHO score generation GEO filter
SET cpd05F=-conf=(pbmc,cpd05j08,GEO,filter) -conf=(balf,cpd05j08,GEO,filter) -conf=(cells,cpd05j08,GEO,filter)
SET cpd07F=-conf=(pbmc,cpd07j08,GEO,filter) -conf=(balf,cpd07j08,GEO,filter) -conf=(cells,cpd07j08,GEO,filter)
SET mdF=-conf=(pbmc,MD,GEO,filter) -conf=(balf,MD,GEO,filter) -conf=(cells,MD,GEO,filter)
SET cpd05NF=-conf=(pbmc,cpd05j08,GEO,nofilter) -conf=(balf,cpd05j08,GEO,nofilter) -conf=(cells,cpd05j08,GEO,nofilter)
SET cpd07NF=-conf=(pbmc,cpd07j08,GEO,nofilter)  -conf=(balf,cpd07j08,GEO,nofilter) -conf=(cells,cpd07j08,GEO,nofilter)
SET mdNF=-conf=(pbmc,MD,GEO,nofilter) -conf=(balf,MD,GEO,nofilter) -conf=(cells,MD,GEO,nofilter)

drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True %cpd05F% %cpd07F% %mdF%  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-01.txt
drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True %cpd05F% %cpd07F% %mdF%   > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-02.txt
drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True %cpd05F% %cpd07F%  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-03.txt
drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  %cpd05F% %cpd07F%  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-04.txt
drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  %cpd05F%  %mdF%  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-05.txt
drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True %cpd05F%  %mdF%  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-06.txt
drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  %cpd07F%  %mdF%  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-07.txt
drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True %cpd07F%  %mdF%  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-08.txt

::ECHO score generation GEO nofilter
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd05j08,GEO,nofilter) -conf=(balf,cpd05j08,GEO,nofilter) -conf=(cells,cpd05j08,GEO,nofilter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-11.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd05j08,GEO,nofilter) -conf=(balf,cpd05j08,GEO,nofilter) -conf=(cells,cpd05j08,GEO,nofilter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-12.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,MD,GEO,nofilter) -conf=(balf,MD,GEO,nofilter) -conf=(cells,MD,GEO,nofilter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-13.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,MD,GEO,nofilter) -conf=(balf,MD,GEO,nofilter) -conf=(cells,MD,GEO,nofilter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-14.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd07j08,GEO,nofilter) -conf=(balf,cpd07j08,GEO,nofilter) -conf=(cells,cpd07j08,GEO,nofilter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-15.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd07j08,GEO,nofilter)  -conf=(balf,cpd07j08,GEO,nofilter) -conf=(cells,cpd07j08,GEO,nofilter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-16.txt

::ECHO score generation DM filter
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd05j08,DM,filter)  -conf=(balf,cpd05j08,DM,filter) -conf=(cells,cpd05j08,DM,filter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-21.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd05j08,DM,filter) -conf=(balf,cpd05j08,DM,filter) -conf=(cells,cpd05j08,DM,filter)  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-22.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,MD,DM,filter) -conf=(balf,MD,DM,filter) -conf=(cells,MD,DM,filter)  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-23.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,MD,DM,filter) -conf=(balf,MD,DM,filter) -conf=(cells,MD,DM,filter)  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-24.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd07j08,DM,filter) -conf=(balf,cpd07j08,DM,filter) -conf=(cells,cpd07j08,DM,filter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-25.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd07j08,DM,filter)  -conf=(balf,cpd07j08,DM,filter) -conf=(cells,cpd07j08,DM,filter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-26.txt

::ECHO score generation DM nofilter
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd05j08,DM,nofilter) -conf=(balf,cpd05j08,DM,nofilter) -conf=(cells,cpd05j08,DM,nofilter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-31.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd05j08,DM,nofilter) -conf=(balf,cpd05j08,DM,nofilter) -conf=(cells,cpd05j08,DM,nofilter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-32.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,MD,DM,nofilter) -conf=(balf,MD,DM,nofilter) -conf=(cells,MD,DM,nofilter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-33.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,MD,DM,nofilter)  -conf=(balf,MD,DM,nofilter) -conf=(cells,MD,DM,nofilter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-34.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd07j08,DM,nofilter) -conf=(balf,cpd07j08,DM,nofilter) -conf=(cells,cpd07j08,DM,nofilter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-35.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd07j08,DM,nofilter) -conf=(balf,cpd07j08,DM,nofilter) -conf=(cells,cpd07j08,DM,nofilter)  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-36.txt

ECHO score generation CMAP filter

SET Ccpd05F=-conf=(pbmc,cpd05j08,CMAP,filter) -conf=(balf,cpd05j08,CMAP,filter) -conf=(cells,cpd05j08,CMAP,filter)
SET Ccpd07F=-conf=(pbmc,cpd07j08,CMAP,filter) -conf=(balf,cpd07j08,CMAP,filter) -conf=(cells,cpd07j08,CMAP,filter)
SET CmdF=-conf=(pbmc,MD,CMAP,filter) -conf=(balf,MD,CMAP,filter) -conf=(cells,MD,CMAP,filter)
SET Ccpd05NF=-conf=(pbmc,cpd05j08,CMAP,nofilter) -conf=(balf,cpd05j08,CMAP,nofilter) -conf=(cells,cpd05j08,CMAP,nofilter)
SET Ccpd07NF=-conf=(pbmc,cpd07j08,CMAP,nofilter)  -conf=(balf,cpd07j08,CMAP,nofilter) -conf=(cells,cpd07j08,CMAP,nofilter)
SET CmdNF=-conf=(pbmc,MD,CMAP,nofilter) -conf=(balf,MD,CMAP,nofilter) -conf=(cells,MD,CMAP,nofilter)

drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  %Ccpd05F% %Ccpd07F%  %CmdF%  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-41.txt
drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True %Ccpd05F% %Ccpd07F%  %CmdF%  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-42.txt
drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  %Ccpd07F%  %CmdF%  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-43.txt
drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  %Ccpd07F%  %CmdF%   > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-44.txt
drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True %Ccpd05F%   %CmdF%  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-45.txt
drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True %Ccpd05F%   %CmdF%  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-46.txt
drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  %Ccpd05F% %Ccpd07F%   > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-47.txt
drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True %Ccpd05F% %Ccpd07F%    > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-48.txt

::ECHO score generation CMAP nofilter
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd05j08,CMAP,nofilter) -conf=(balf,cpd05j08,CMAP,nofilter)  -conf=(cells,cpd05j08,CMAP,nofilter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-51.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd05j08,CMAP,nofilter) -conf=(balf,cpd05j08,CMAP,nofilter)  -conf=(cells,cpd05j08,CMAP,nofilter)  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-52.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,MD,CMAP,nofilter) -conf=(balf,MD,CMAP,nofilter) -conf=(cells,MD,CMAP,nofilter)  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-53.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,MD,CMAP,nofilter) -conf=(balf,MD,CMAP,nofilter) -conf=(cells,MD,CMAP,nofilter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-54.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd07j08,CMAP,nofilter) -conf=(balf,cpd07j08,CMAP,nofilter) -conf=(cells,cpd07j08,CMAP,nofilter)  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-55.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd07j08,CMAP,nofilter) -conf=(balf,cpd07j08,CMAP,nofilter) -conf=(cells,cpd07j08,CMAP,nofilter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-56.txt

::ECHO score generation L1000 filter
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd05j08,L1000,filter) -conf=(balf,cpd05j08,L1000,filter) -conf=(cells,cpd05j08,L1000,filter)  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-61.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd05j08,L1000,filter) -conf=(balf,cpd05j08,L1000,filter) -conf=(cells,cpd05j08,L1000,filter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-62.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,MD,L1000,filter) -conf=(balf,MD,L1000,filter) -conf=(cells,MD,L1000,filter)  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-63.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,MD,L1000,filter) -conf=(balf,MD,L1000,filter) -conf=(cells,MD,L1000,filter)  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-64.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd07j08,L1000,filter) -conf=(balf,cpd07j08,L1000,filter) -conf=(cells,cpd07j08,L1000,filter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-65.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd07j08,L1000,filter) -conf=(balf,cpd07j08,L1000,filter) -conf=(cells,cpd07j08,L1000,filter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-66.txt

::ECHO score generation L1000 nofilter
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,MD,L1000,nofilter) -conf=(balf,cpd05j08,L1000,nofilter) -conf=(cells,cpd05j08,L1000,nofilter)  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-71.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,MD,L1000,nofilter) -conf=(balf,cpd05j08,L1000,nofilter) -conf=(cells,cpd05j08,L1000,nofilter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-72.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd07j08,L1000,nofilter) -conf=(balf,MD,L1000,nofilter) -conf=(cells,MD,L1000,nofilter)  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-73.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd07j08,L1000,nofilter) -conf=(balf,MD,L1000,nofilter) -conf=(cells,MD,L1000,nofilter) > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-74.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=size_x_deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd05j08,L1000,nofilter)  -conf=(balf,cpd07j08,L1000,nofilter) -conf=(cells,cpd07j08,L1000,nofilter)  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-75.txt
::drugranking_by_direction.py --combinations=False --reuse=True  --weights=deltadeg --fdadrugsonly=True  --positiveonly=True  -conf=(pbmc,cpd05j08,L1000,nofilter)  -conf=(balf,cpd07j08,L1000,nofilter) -conf=(cells,cpd07j08,L1000,nofilter)  > ./modulation-covid19-pbmc-results-score-fdaonly-posonly/global-filter-covid19-all-2021-03-26-laptop-76.txt

PAUSE
