#!/bin/csh
#
echo score generation GEO filter
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd05j08,GEO,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-01.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd05j08,GEO,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-02.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,MD,GEO,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-03.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,MD,GEO,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-04.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd07j08,GEO,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-05.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd07j08,GEO,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-06.txt  
#
echo score generation GEO nofilter
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd05j08,GEO,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-11.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd05j08,GEO,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-12.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,MD,GEO,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-13.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,MD,GEO,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-14.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd07j08,GEO,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-15.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd07j08,GEO,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-16.txt  
#
echo score generation DM filter
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd05j08,DM,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-21.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd05j08,DM,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-22.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,MD,DM,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-23.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,MD,DM,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-24.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd07j08,DM,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-25.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd07j08,DM,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-26.txt  
#
echo score generation DM nofilter
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd05j08,DM,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-31.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd05j08,DM,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-32.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,MD,DM,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-33.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,MD,DM,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-34.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd07j08,DM,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-35.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd07j08,DM,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-36.txt  
#
echo score generation CMAP filter
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd05j08,CMAP,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-41.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd05j08,CMAP,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-42.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,MD,CMAP,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-43.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,MD,CMAP,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-44.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd07j08,CMAP,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-45.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd07j08,CMAP,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-46.txt  
#
echo score generation CMAP nofilter
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd05j08,CMAP,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-51.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd05j08,CMAP,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-52.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,MD,CMAP,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-53.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,MD,CMAP,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-54.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd07j08,CMAP,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-55.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd07j08,CMAP,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-56.txt  
#
echo score generation L1000 filter
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd05j08,L1000,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-61.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd05j08,L1000,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-62.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,MD,L1000,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-63.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,MD,L1000,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-64.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd07j08,L1000,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-65.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd07j08,L1000,filter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-66.txt  
#
echo score generation L1000 nofilter
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,MD,L1000,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-71.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,MD,L1000,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-72.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd07j08,L1000,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-73.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd07j08,L1000,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-74.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=size_x_deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd05j08,L1000,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-75.txt  
python drugranking_by_direction.py --combinations=False --reuse=False  --weights=deltadeg --fdadrugsonly=False  --positiveonly=True  -conf=\(cells,cpd05j08,L1000,nofilter\)  > ./modulation-covid19-cells-results-score-nofda-posonly/test-filter-covid19-cells-2021-03-13-76.txt  


